fix: make the main workshop TS code compile (#171)
Without exporting the CdkWorkshopStack class,
`npm run build` fails with:

```
lib/cdk-workshop-stack.ts(7,7): error TS6196: 'CdkWorkshopStack' is declared but never used.
```