chore: Bump aws-cdk-lib from 2.116.1 to 2.117.0 in /cdkworkshop.com (#1288)
Bumps [aws-cdk-lib](https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib) from 2.116.1 to 2.117.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/aws/aws-cdk/releases">aws-cdk-lib's releases</a>.</em></p>
<blockquote>
<h2>v2.117.0</h2>
<h3>Features</h3>
<ul>
<li>update L1 CloudFormation resource definitions (<a href="https://redirect.github.com/aws/aws-cdk/issues/28489">#28489</a>) (<a href="https://github.com/aws/aws-cdk/commit/607dccb0fd920d25f0fe2613b83c9830322c439e">607dccb</a>), closes <a href="https://github.com/aws//docs.aws.amazon.com/datasync/latest/userguide/working-with-locations.html/issues/create-s3">/docs.aws.amazon.com/datasync/latest/userguide/working-with-locations.html#create-s3</a></li>
<li><strong>api-gateway-v2:</strong> Add method to generate flexible execute-api ARN (<a href="https://redirect.github.com/aws/aws-cdk/issues/28400">#28400</a>) (<a href="https://github.com/aws/aws-cdk/commit/09320276c2c08ace1d85b970fe91bc1bea208457">0932027</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/23301">#23301</a></li>
<li><strong>autoscaling:</strong> instance maintenance policy for AutoScalingGroup (<a href="https://redirect.github.com/aws/aws-cdk/issues/28092">#28092</a>) (<a href="https://github.com/aws/aws-cdk/commit/5eb2c262141d197073173037fc350c26920b774f">5eb2c26</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28042">#28042</a></li>
<li><strong>codebuild:</strong> Lambda compute for codebuild projects (<a href="https://redirect.github.com/aws/aws-cdk/issues/27934">#27934</a>) (<a href="https://github.com/aws/aws-cdk/commit/a4a4c6f19719b9238e2f397d0049af867846ad94">a4a4c6f</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28418">#28418</a></li>
<li><strong>core:</strong> option to disable cache for docker build (<a href="https://redirect.github.com/aws/aws-cdk/issues/27944">#27944</a>) (<a href="https://github.com/aws/aws-cdk/commit/84d81b67ee2574c98c4a26d8b5c567be84b6cf02">84d81b6</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27916">#27916</a></li>
<li><strong>ec2:</strong> trn1 instance type (<a href="https://redirect.github.com/aws/aws-cdk/issues/28477">#28477</a>) (<a href="https://github.com/aws/aws-cdk/commit/ed02d5c148a9412e92ee62d35560526b14cfc907">ed02d5c</a>)</li>
<li><strong>ecs:</strong> Implement method in ECS cluster to retrieve task ARN (<a href="https://redirect.github.com/aws/aws-cdk/issues/28381">#28381</a>) (<a href="https://github.com/aws/aws-cdk/commit/7635bbc9b4d766a7920747dd73c571bee90895f9">7635bbc</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/26232">#26232</a></li>
<li><strong>ecs-patterns:</strong> support disabling CPU-based scaling and custom target utilization (<a href="https://redirect.github.com/aws/aws-cdk/issues/28315">#28315</a>) (<a href="https://github.com/aws/aws-cdk/commit/3cb3e0299ee427a02161a4e5bb250dad8ab3909a">3cb3e02</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/20706">#20706</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/20706">#20706</a></li>
<li><strong>elasticloadbalancingv2:</strong> dualstack NetworkLoadBalancer (<a href="https://redirect.github.com/aws/aws-cdk/issues/27546">#27546</a>) (<a href="https://github.com/aws/aws-cdk/commit/e03a41f5cbafda74a193cd64955674e59a654a78">e03a41f</a>), closes <a href="https://github.com/aws//docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html/issues/cfn-elasticloadbalancingv2">/docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/27538">#27538</a></li>
<li><strong>elasticloadbalancingv2:</strong> FIPS compliant SSL policy to ALB (<a href="https://redirect.github.com/aws/aws-cdk/issues/28479">#28479</a>) (<a href="https://github.com/aws/aws-cdk/commit/7bb72e1e1bcc84f45ebe714e379fa085a5642355">7bb72e1</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28455">#28455</a></li>
<li><strong>globalaccelerator:</strong> add support for ip addresses and type (<a href="https://redirect.github.com/aws/aws-cdk/issues/28055">#28055</a>) (<a href="https://github.com/aws/aws-cdk/commit/943abe877cfbcbb54311e2ecc4a9a3bfb231a202">943abe8</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28051">#28051</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28209">#28209</a></li>
<li><strong>ses:</strong> synth-time naming validation for dedicatedIpPoolName (<a href="https://redirect.github.com/aws/aws-cdk/issues/28466">#28466</a>) (<a href="https://github.com/aws/aws-cdk/commit/be6ddb88cce057ef23ff8fee67a4f5b3f063a931">be6ddb8</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28451">#28451</a></li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> core constructs fail with <code>Error: Cannot find module '../dist/core/&lt;file&gt;.generated'</code> (<a href="https://redirect.github.com/aws/aws-cdk/issues/28467">#28467</a>) (<a href="https://github.com/aws/aws-cdk/commit/cd54c4239ec29182e30fd91634505df560d6e5f8">cd54c42</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28465">#28465</a></li>
<li><strong>ecs-patterns:</strong> <code>ApplicationMultipleTargetGroupsEc2Service</code> ignores load balancer name (<a href="https://redirect.github.com/aws/aws-cdk/issues/28394">#28394</a>) (<a href="https://github.com/aws/aws-cdk/commit/9c0fecf9a5cc26416e814ae4754729b54c827b9d">9c0fecf</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/23535">#23535</a></li>
</ul>
<hr />
<h2>Alpha modules (2.117.0-alpha.0)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>lambda-python-alpha:</strong> bundling hash logic includes auth tokens in PIP urls, causing an unnecessary rebuild (<a href="https://redirect.github.com/aws/aws-cdk/issues/27903">#27903</a>) (<a href="https://github.com/aws/aws-cdk/commit/00331a7292a3e60ea5ba3caf2a4fd4cca2fe7dc5">00331a7</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27331">#27331</a></li>
<li><strong>lambda-python-alpha:</strong> use function architecture (<a href="https://redirect.github.com/aws/aws-cdk/issues/18696">#18696</a>) (<a href="https://redirect.github.com/aws/aws-cdk/issues/28449">#28449</a>) (<a href="https://github.com/aws/aws-cdk/commit/c724d277277c45b421dcd89ee1a6d4b54f942d3b">c724d27</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/aws/aws-cdk/blob/main/CHANGELOG.v2.md">aws-cdk-lib's changelog</a>.</em></p>
<blockquote>
<h2><a href="https://github.com/aws/aws-cdk/compare/v2.116.1...v2.117.0">2.117.0</a> (2023-12-26)</h2>
<h3>Features</h3>
<ul>
<li>update L1 CloudFormation resource definitions (<a href="https://redirect.github.com/aws/aws-cdk/issues/28489">#28489</a>) (<a href="https://github.com/aws/aws-cdk/commit/607dccb0fd920d25f0fe2613b83c9830322c439e">607dccb</a>), closes <a href="https://github.com/aws//docs.aws.amazon.com/datasync/latest/userguide/working-with-locations.html/issues/create-s3">/docs.aws.amazon.com/datasync/latest/userguide/working-with-locations.html#create-s3</a></li>
<li><strong>api-gateway-v2:</strong> Add method to generate flexible execute-api ARN (<a href="https://redirect.github.com/aws/aws-cdk/issues/28400">#28400</a>) (<a href="https://github.com/aws/aws-cdk/commit/09320276c2c08ace1d85b970fe91bc1bea208457">0932027</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/23301">#23301</a></li>
<li><strong>autoscaling:</strong> instance maintenance policy for AutoScalingGroup (<a href="https://redirect.github.com/aws/aws-cdk/issues/28092">#28092</a>) (<a href="https://github.com/aws/aws-cdk/commit/5eb2c262141d197073173037fc350c26920b774f">5eb2c26</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28042">#28042</a></li>
<li><strong>codebuild:</strong> Lambda compute for codebuild projects (<a href="https://redirect.github.com/aws/aws-cdk/issues/27934">#27934</a>) (<a href="https://github.com/aws/aws-cdk/commit/a4a4c6f19719b9238e2f397d0049af867846ad94">a4a4c6f</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28418">#28418</a></li>
<li><strong>core:</strong> option to disable cache for docker build (<a href="https://redirect.github.com/aws/aws-cdk/issues/27944">#27944</a>) (<a href="https://github.com/aws/aws-cdk/commit/84d81b67ee2574c98c4a26d8b5c567be84b6cf02">84d81b6</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27916">#27916</a></li>
<li><strong>ec2:</strong> trn1 instance type (<a href="https://redirect.github.com/aws/aws-cdk/issues/28477">#28477</a>) (<a href="https://github.com/aws/aws-cdk/commit/ed02d5c148a9412e92ee62d35560526b14cfc907">ed02d5c</a>)</li>
<li><strong>ecs:</strong> Implement method in ECS cluster to retrieve task ARN (<a href="https://redirect.github.com/aws/aws-cdk/issues/28381">#28381</a>) (<a href="https://github.com/aws/aws-cdk/commit/7635bbc9b4d766a7920747dd73c571bee90895f9">7635bbc</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/26232">#26232</a></li>
<li><strong>ecs-patterns:</strong> support disabling CPU-based scaling and custom target utilization (<a href="https://redirect.github.com/aws/aws-cdk/issues/28315">#28315</a>) (<a href="https://github.com/aws/aws-cdk/commit/3cb3e0299ee427a02161a4e5bb250dad8ab3909a">3cb3e02</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/20706">#20706</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/20706">#20706</a></li>
<li><strong>elasticloadbalancingv2:</strong> dualstack NetworkLoadBalancer (<a href="https://redirect.github.com/aws/aws-cdk/issues/27546">#27546</a>) (<a href="https://github.com/aws/aws-cdk/commit/e03a41f5cbafda74a193cd64955674e59a654a78">e03a41f</a>), closes <a href="https://github.com/aws//docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html/issues/cfn-elasticloadbalancingv2">/docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/27538">#27538</a></li>
<li><strong>elasticloadbalancingv2:</strong> FIPS compliant SSL policy to ALB (<a href="https://redirect.github.com/aws/aws-cdk/issues/28479">#28479</a>) (<a href="https://github.com/aws/aws-cdk/commit/7bb72e1e1bcc84f45ebe714e379fa085a5642355">7bb72e1</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28455">#28455</a></li>
<li><strong>globalaccelerator:</strong> add support for ip addresses and type (<a href="https://redirect.github.com/aws/aws-cdk/issues/28055">#28055</a>) (<a href="https://github.com/aws/aws-cdk/commit/943abe877cfbcbb54311e2ecc4a9a3bfb231a202">943abe8</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28051">#28051</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28209">#28209</a></li>
<li><strong>ses:</strong> synth-time naming validation for dedicatedIpPoolName (<a href="https://redirect.github.com/aws/aws-cdk/issues/28466">#28466</a>) (<a href="https://github.com/aws/aws-cdk/commit/be6ddb88cce057ef23ff8fee67a4f5b3f063a931">be6ddb8</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28451">#28451</a></li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> core constructs fail with <code>Error: Cannot find module '../dist/core/&lt;file&gt;.generated'</code> (<a href="https://redirect.github.com/aws/aws-cdk/issues/28467">#28467</a>) (<a href="https://github.com/aws/aws-cdk/commit/cd54c4239ec29182e30fd91634505df560d6e5f8">cd54c42</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28465">#28465</a></li>
<li><strong>ecs-patterns:</strong> <code>ApplicationMultipleTargetGroupsEc2Service</code> ignores load balancer name (<a href="https://redirect.github.com/aws/aws-cdk/issues/28394">#28394</a>) (<a href="https://github.com/aws/aws-cdk/commit/9c0fecf9a5cc26416e814ae4754729b54c827b9d">9c0fecf</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/23535">#23535</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/aws/aws-cdk/commit/9c0fecf9a5cc26416e814ae4754729b54c827b9d"><code>9c0fecf</code></a> fix(ecs-patterns): <code>ApplicationMultipleTargetGroupsEc2Service</code> ignores load b...</li>
<li><a href="https://github.com/aws/aws-cdk/commit/607dccb0fd920d25f0fe2613b83c9830322c439e"><code>607dccb</code></a> feat: update L1 CloudFormation resource definitions (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/28489">#28489</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/e03a41f5cbafda74a193cd64955674e59a654a78"><code>e03a41f</code></a> feat(elasticloadbalancingv2): dualstack NetworkLoadBalancer (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/27546">#27546</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/00331a7292a3e60ea5ba3caf2a4fd4cca2fe7dc5"><code>00331a7</code></a> fix(lambda-python-alpha): bundling hash logic includes auth tokens in PIP url...</li>
<li><a href="https://github.com/aws/aws-cdk/commit/84d81b67ee2574c98c4a26d8b5c567be84b6cf02"><code>84d81b6</code></a> feat(core): option to disable cache for docker build (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/27944">#27944</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/7bb72e1e1bcc84f45ebe714e379fa085a5642355"><code>7bb72e1</code></a> feat(elasticloadbalancingv2): FIPS compliant SSL policy to ALB (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/28479">#28479</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/ed02d5c148a9412e92ee62d35560526b14cfc907"><code>ed02d5c</code></a> feat(ec2): trn1 instance type (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/28477">#28477</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/a4a4c6f19719b9238e2f397d0049af867846ad94"><code>a4a4c6f</code></a> feat(codebuild): Lambda compute for codebuild projects (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/27934">#27934</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/5eb2c262141d197073173037fc350c26920b774f"><code>5eb2c26</code></a> feat(autoscaling): instance maintenance policy for AutoScalingGroup (<a href="https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib/issues/28092">#28092</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/3cb3e0299ee427a02161a4e5bb250dad8ab3909a"><code>3cb3e02</code></a> feat(ecs-patterns): support disabling CPU-based scaling and custom target uti...</li>
<li>Additional commits viewable in <a href="https://github.com/aws/aws-cdk/commits/v2.117.0/packages/aws-cdk-lib">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=aws-cdk-lib&package-manager=npm_and_yarn&previous-version=2.116.1&new-version=2.117.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>