Fix syntax error - missing attribute
cdkworkshop_stack.py",
    apigw.LambdaRestApi(self, 'Endpoint', handler=hello_with_counter.handler, )
AttributeError: 'HitCounter' object has no attribute 'handler'