Update 5000-test-actions.md
Need to add the table viewer to the requirement file, otherwise, an error like the following will be thrown.


[Container] 2022/08/19 22:06:48 Running command cdk synth
Traceback (most recent call last):
  File "/codebuild/output/src236959413/src/app.py", line 6, in <module>
    from cdk_workshop.pipeline_stack import WorkshopPipelineStack
  File "/codebuild/output/src236959413/src/cdk_workshop/pipeline_stack.py", line 7, in <module>
    from cdk_workshop.pipeline_stage import WorkshopPipelineStage
  File "/codebuild/output/src236959413/src/cdk_workshop/pipeline_stage.py", line 5, in <module>
    from .cdk_workshop_stack import CdkWorkshopStack
  File "/codebuild/output/src236959413/src/cdk_workshop/cdk_workshop_stack.py", line 15, in <module>
    from cdk_dynamo_table_view import TableViewer
ModuleNotFoundError: No module named 'cdk_dynamo_table_view'