chore: Update aws-cdk-lib requirement from ~=2.115 to ~=2.116 in /code/python (#1280)
Updates the requirements on [aws-cdk-lib](https://github.com/aws/aws-cdk) to permit the latest version.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/aws/aws-cdk/releases">aws-cdk-lib's releases</a>.</em></p>
<blockquote>
<h2>v2.116.1</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> core constructs fail with <code>Error: Cannot find module '../dist/core/&lt;file&gt;.generated'</code> (<a href="https://redirect.github.com/aws/aws-cdk/issues/28467">#28467</a>) (<a href="https://github.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933">e8be128</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28465">#28465</a></li>
</ul>
<hr />
<h2>Alpha modules (2.116.1-alpha.0)</h2>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/aws/aws-cdk/blob/main/CHANGELOG.v2.md">aws-cdk-lib's changelog</a>.</em></p>
<blockquote>
<h2><a href="https://github.com/aws/aws-cdk/compare/v2.116.0...v2.116.1">2.116.1</a> (2023-12-22)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> core constructs fail with <code>Error: Cannot find module '../dist/core/&lt;file&gt;.generated'</code> (<a href="https://redirect.github.com/aws/aws-cdk/issues/28467">#28467</a>) (<a href="https://github.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933">e8be128</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28465">#28465</a></li>
</ul>
<h2><a href="https://github.com/aws/aws-cdk/compare/v2.115.0...v2.116.0">2.116.0</a> (2023-12-21)</h2>
<h3>Features</h3>
<ul>
<li><strong>apigateway:</strong> validate integrationHttpMethod with non-MOCK integration types (<a href="https://redirect.github.com/aws/aws-cdk/issues/28316">#28316</a>) (<a href="https://github.com/aws/aws-cdk/commit/93cb6e4399fe0e2de67050f10920ec7a1eda34e1">93cb6e4</a>)</li>
<li><strong>ec2:</strong> support creating key pairs (<a href="https://redirect.github.com/aws/aws-cdk/issues/28138">#28138</a>) (<a href="https://github.com/aws/aws-cdk/commit/6b3caff7ac4321ca79e70821991de041d33eaa7c">6b3caff</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/5252">#5252</a></li>
<li><strong>ecr:</strong> Add emptyOnDelete CloudFormation property to Repository L2 construct (<a href="https://redirect.github.com/aws/aws-cdk/issues/28233">#28233</a>) (<a href="https://github.com/aws/aws-cdk/commit/a175da8ec1f4d6149efdfe05749d77ae104842d4">a175da8</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/24572">#24572</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28196">#28196</a></li>
<li><strong>ecr:</strong> tag pattern list for lifecycle policy (<a href="https://redirect.github.com/aws/aws-cdk/issues/28432">#28432</a>) (<a href="https://github.com/aws/aws-cdk/commit/aa075cd07a892e6c1d5243d5526e2c8658b98621">aa075cd</a>)</li>
<li><strong>ecs:</strong> log retention for FireLensLogDriver (<a href="https://redirect.github.com/aws/aws-cdk/issues/28354">#28354</a>) (<a href="https://github.com/aws/aws-cdk/commit/52a5579aa52c88bb289a7a9677c35385763c8fff">52a5579</a>), closes <a href="https://github.com/aws//github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts/issues/L816">/github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts#L816</a> <a href="https://github.com/aws//github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/firelens-log-router.ts/issues/L170">/github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/firelens-log-router.ts#L170</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/28258">#28258</a></li>
<li><strong>ecs:</strong> Support specifying revision of task definition (<a href="https://redirect.github.com/aws/aws-cdk/issues/27036">#27036</a>) (<a href="https://github.com/aws/aws-cdk/commit/de0d77b2075506f3c28e657fa072a0bffc8c734a">de0d77b</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/26983">#26983</a></li>
<li><strong>events:</strong> add multiple event bus policies on a single event bus (<a href="https://redirect.github.com/aws/aws-cdk/issues/27340">#27340</a>) (<a href="https://github.com/aws/aws-cdk/commit/4dde5021a4e69de0ca2e49226ef0d2cde76d4235">4dde502</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/24671">#24671</a></li>
<li><strong>rds:</strong> support aurora mysql 3.05.1 (<a href="https://redirect.github.com/aws/aws-cdk/issues/28370">#28370</a>) (<a href="https://github.com/aws/aws-cdk/commit/986db38842c901bfe50098b36d78d6e3a6befdf1">986db38</a>)</li>
<li><strong>ses:</strong> add scalingMode property to dedicated ip pool (<a href="https://redirect.github.com/aws/aws-cdk/issues/28392">#28392</a>) (<a href="https://github.com/aws/aws-cdk/commit/c6877788f7abd19b4dcc792d5fa73fc118410efd">c687778</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27418">#27418</a></li>
<li><strong>sns:</strong> delivery status logging configuration (<a href="https://redirect.github.com/aws/aws-cdk/issues/28433">#28433</a>) (<a href="https://github.com/aws/aws-cdk/commit/36bb6967ad28a84b68e7b9ea5d5facadf0de4297">36bb696</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/21971">#21971</a></li>
<li><strong>stepfunctions:</strong> CustomState addCatch (<a href="https://redirect.github.com/aws/aws-cdk/issues/28422">#28422</a>) (<a href="https://github.com/aws/aws-cdk/commit/cf923bc4eacd3bb0efdc469708dc389a67d38bcc">cf923bc</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/25798">#25798</a></li>
<li><strong>stepfunctions:</strong> support Map ItemProcessor (<a href="https://redirect.github.com/aws/aws-cdk/issues/27913">#27913</a>) (<a href="https://github.com/aws/aws-cdk/commit/ac417301348f3bc2f0b7352c032802c2aff8d721">ac41730</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27878">#27878</a></li>
<li><strong>stepfunctions-tasks:</strong> EMR createCluster command support OnDemandSpecification (<a href="https://redirect.github.com/aws/aws-cdk/issues/27791">#27791</a>) (<a href="https://github.com/aws/aws-cdk/commit/73a5e740e7556c8b59111ab4602125ac78a5364f">73a5e74</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27761">#27761</a></li>
<li>implement code generated handler framework (<a href="https://redirect.github.com/aws/aws-cdk/issues/28251">#28251</a>) (<a href="https://github.com/aws/aws-cdk/commit/1a9c30e55e58203bd0a61de82711cf10f1e04851">1a9c30e</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27303">#27303</a></li>
<li>update AWS Service Spec (<a href="https://redirect.github.com/aws/aws-cdk/issues/28407">#28407</a>) (<a href="https://github.com/aws/aws-cdk/commit/fcb701ceb7288be5307a0f9c12826a13d97251b7">fcb701c</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>core:</strong> messages from <code>annotations.ts</code> can show up as <code>[object Object]</code> (<a href="https://redirect.github.com/aws/aws-cdk/issues/28414">#28414</a>) (<a href="https://github.com/aws/aws-cdk/commit/3e6f10ddfdf93147f3d488de2965f7e263bd1713">3e6f10d</a>)</li>
<li><strong>custom-resources:</strong> cannot set logging for state machine generated in CompleteHandler (<a href="https://redirect.github.com/aws/aws-cdk/issues/27310">#27310</a>) (<a href="https://github.com/aws/aws-cdk/commit/bfeef00c5e1d99415ff2135054e35acc5e9f6b93">bfeef00</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27283">#27283</a></li>
<li><strong>ecs-patterns:</strong> taskDefinition ignored by queueProcessingFargateService (<a href="https://redirect.github.com/aws/aws-cdk/issues/28220">#28220</a>) (<a href="https://github.com/aws/aws-cdk/commit/5d6b8eefc66d326325673bda2b86b72aa4579199">5d6b8ee</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27360">#27360</a></li>
<li><strong>eks:</strong> neuron plugin not added with addNodegroupCapacity() (<a href="https://redirect.github.com/aws/aws-cdk/issues/27909">#27909</a>) (<a href="https://github.com/aws/aws-cdk/commit/b87212b9fe2064b97d8935db49e6d78e183c2fd8">b87212b</a>)</li>
<li><strong>events-targets:</strong> imported sqs queue cannot be used as a rule dlq (<a href="https://redirect.github.com/aws/aws-cdk/issues/28165">#28165</a>) (<a href="https://redirect.github.com/aws/aws-cdk/issues/28285">#28285</a>) (<a href="https://github.com/aws/aws-cdk/commit/588b1064c289295c5acce1b991ef8dcd7c8bec3f">588b106</a>)</li>
<li><strong>iam:</strong> importedRoleStackSafeDefaultPolicyName feature flag results in excessively long IAM policy names (<a href="https://redirect.github.com/aws/aws-cdk/issues/27548">#27548</a>) (<a href="https://github.com/aws/aws-cdk/commit/4f88db691652274eb1b3119c8b1dccb196b29928">4f88db6</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27409">#27409</a> <a href="https://redirect.github.com/aws/aws-cdk/issues/24441">#24441</a></li>
<li><strong>logs:</strong> adding a resource policy statement with <code>AnyPrincipal</code> fails (<a href="https://redirect.github.com/aws/aws-cdk/issues/27787">#27787</a>) (<a href="https://github.com/aws/aws-cdk/commit/0b2ba1c5d807ce8dfc390ea3b0ca5a1e39636315">0b2ba1c</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/27783">#27783</a></li>
<li><strong>s3-notifications:</strong> multiple notifications doesn't work (<a href="https://redirect.github.com/aws/aws-cdk/issues/28132">#28132</a>) (<a href="https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8">37be7b9</a>)</li>
<li><strong>secretsmanager:</strong> cannot set hourly rotation (<a href="https://redirect.github.com/aws/aws-cdk/issues/28303">#28303</a>) (<a href="https://github.com/aws/aws-cdk/commit/09cb003fb917714c0dc88b47cd05893c2a816d45">09cb003</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28261">#28261</a></li>
<li><strong>secretsmanager:</strong> hosted rotation with fromSecretNameV2() does not create correct iam policy (<a href="https://redirect.github.com/aws/aws-cdk/issues/28379">#28379</a>) (<a href="https://github.com/aws/aws-cdk/commit/4ab5bb2e9aab4cee4e8a2bcd81871254f2c3065f">4ab5bb2</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28308">#28308</a></li>
</ul>
<h2><a href="https://github.com/aws/aws-cdk/compare/v2.114.1...v2.115.0">2.115.0</a> (2023-12-14)</h2>
<h3>Features</h3>
<ul>
<li><strong>eks:</strong> support Bottlerocket Nvidia AMIs (<a href="https://redirect.github.com/aws/aws-cdk/issues/28287">#28287</a>) (<a href="https://github.com/aws/aws-cdk/commit/6aa1b1b02ab3782b0e6419f8d5a340663cb47c81">6aa1b1b</a>), closes <a href="https://redirect.github.com/aws/aws-cdk/issues/28241">#28241</a></li>
<li><strong>rds:</strong> support RDS for MariaDB 10.11.6, 10.6.16, 10.5.23 and 10.4.32 (<a href="https://redirect.github.com/aws/aws-cdk/issues/28345">#28345</a>) (<a href="https://github.com/aws/aws-cdk/commit/0347a19e49533971e4e57b7e04271dffc541ff92">0347a19</a>)</li>
<li><strong>rds:</strong> support RDS for SQL Server 16.00.4095.4.v1 (<a href="https://redirect.github.com/aws/aws-cdk/issues/28274">#28274</a>) (<a href="https://github.com/aws/aws-cdk/commit/7a22501d58912f777ae0a2ad1b48af2faeb6946b">7a22501</a>)</li>
</ul>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/aws/aws-cdk/commit/222de7116ffd1ce07c1215970884a0ca59b3cbc9"><code>222de71</code></a> chore(release): 2.116.1 (<a href="https://redirect.github.com/aws/aws-cdk/issues/28468">#28468</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/557ed28831bec38f753d5352b651097cf0b159f7"><code>557ed28</code></a> chore(release): 2.116.1</li>
<li><a href="https://github.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933"><code>e8be128</code></a> fix(core): core constructs fail with `Error: Cannot find module '../dist/core...</li>
<li><a href="https://github.com/aws/aws-cdk/commit/a1552da95d65d222195d542055873f5c07eb0bf6"><code>a1552da</code></a> chore(release): 2.116.0 (<a href="https://redirect.github.com/aws/aws-cdk/issues/28458">#28458</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/1ed9b5211f65ff47adee2c4150d11f3e3892b876"><code>1ed9b52</code></a> Merge branch 'v2-release' into bump/2.116.0</li>
<li><a href="https://github.com/aws/aws-cdk/commit/729db12c0ba7161518b29f94d70fa63f159d62ae"><code>729db12</code></a> chore(release): 2.116.0</li>
<li><a href="https://github.com/aws/aws-cdk/commit/16a1a6206ed2e1553bbb170c68b3cd0f5770706f"><code>16a1a62</code></a> chore(integ-tests): revert add waiterProvider to IApiCall (<a href="https://redirect.github.com/aws/aws-cdk/issues/28457">#28457</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/5344e87bb2f462bb0742031541bcb4435a1150b8"><code>5344e87</code></a> chore(release): 2.116.0 (<a href="https://redirect.github.com/aws/aws-cdk/issues/28456">#28456</a>)</li>
<li><a href="https://github.com/aws/aws-cdk/commit/3b4d4a5ee07ce40702976edd5d7f22f71693bb13"><code>3b4d4a5</code></a> chore(release): 2.116.0</li>
<li><a href="https://github.com/aws/aws-cdk/commit/9ca7ba8e5d79917a167e7c411d3e73f8e674def4"><code>9ca7ba8</code></a> chore(integ-tests): add waiterProvider to IApiCall (<a href="https://redirect.github.com/aws/aws-cdk/issues/27844">#27844</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/aws/aws-cdk/compare/v2.115.0...v2.116.1">compare view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>